### ISSUE TITLE
ngMask tilts browser when including optional characters ("?") and/or mask-repeat > 50

### ISSUE THREAD

**Issue by ncarreiro** [candreoliveira/ngMask#100]
I'm having a bug when using ngMask when creating an input with this structure:

`<input type="text" ng-model="full_name" placeholder="Hola" mask="@?s?" clean="true" repeat="150"></input>`

The specific problem happens when using this mask for a Full Name form input (I want to be able to type letters and white-spaces, but no numbers, special characters or other things). The only possible option I thought with the Docs is this one, but when using a repeat value > 50 and typing an invalid and restricted character, the browser (both Chrome and Firefox) tilts and can't be refreshed, closed or anything. Only killing the process works. It also tilts when reaching the repeat attribute value.

What could be the problem? I've already tried using this <input> in the index.html to prevent problems with other directives I use like Modals, Wizards, etc. The directive impacts a lot in website loading time as well.

**Comment by linegrunwald** [comment]
Were you able to solve this problem?

**Comment by ncarreiro** [comment]
Nope. The only solution I had was repeating the same mask logic 150 times... but that's terrible for code reading quality. I think I just made a RegEx mask validation for this input on every ng-change.

**Comment by linegrunwald** [comment]
It really is very annoying.
Or create a directve.

app.directive('noSpecialChar', function() {
return {
  require: 'ngModel',
  restrict: 'A',
  link: function(scope, element, attrs, modelCtrl) {
    modelCtrl.$parsers.push(function(inputValue) {
      if (inputValue == null)
        return ''
      cleanInputValue = inputValue.replace(/[^\w\s]/gi, '');
      if (cleanInputValue != inputValue) {
        modelCtrl.$setViewValue(cleanInputValue);
        modelCtrl.$render();
      }
      return cleanInputValue;
    });
  }
} });
according: 
[How to restrict special characters in angularjs textbox [closed]
](https://stackoverflow.com/questions/34062276/how-to-restrict-special-characters-in-angularjs-textbox)
