### ISSUE TITLE
How to optionally allow negative numbers?

### ISSUE THREAD

**Issue by OlgerCA** [candreoliveira/ngMask#114]
Hi! Is there any way to optionally allow negative numbers? For example allow both 99 and -99 as valid inputs?

Thanks

**Comment by mr-raptor** [comment]
Hi, you can try something like this:
`<input type="text" ng-model="maskModel" mask="*99?" restrict="reject" validate="false" data-ng-pattern="/^(-(\d){1,2}|(\d){1,3})$/" />`

**Comment by OlgerCA** [comment]
Thank you so much! I will give it a try. :)
