### ISSUE TITLE
Seems, that mask rejection isn't working

### ISSUE THREAD

**Issue by jeserkin** [candreoliveira/ngMask#22]
Looked through examples, located here http://candreoliveira.github.io/bower_components/angular-mask/examples/#/.

All date examples with `restrict` set to `reject` are not working as far as I can tell. Maybe I'm missing something?

If mask is `MASK: 19/39/9999` and `RESTRICT: REJECT`, then I would assume, that nothing beside this `19/39/9999` shoud be allowed to be inserted.

**Comment by candreoliveira** [comment]
The rejection is applied to invalid characters. Those chars aren't inserted with selection to show the user mistake according mask.
