### ISSUE TITLE
NPM support

### ISSUE THREAD

**Issue by atwright147** [candreoliveira/ngMask#35]
Hi,

Awesome directive.

I need to start using this via NPM rather than bower. The package name in package.json is a bit unclear as just "mask" and it does not seem to have been registered in the NPM registry.

Would you please rename it to "ngMask" and register on the registry...

Cheers,

Andy

**Comment by atwright147** [comment]
I have sent a pull request: https://github.com/candreoliveira/ngMask/pull/36

**Comment by JobaDiniz** [comment]
I have found this one (https://www.npmjs.com/package/ng-mask) but it is not an official

**Comment by TheLarkInn** [comment]
+1 This should really be added to npm registry.

**Comment by aaronroberson** [comment]
I've reached out to @enriquecastl for permissions to publish the official ngMask to the npm registry under `ng-mask`.
