### ISSUE TITLE
problem in version angular 1.4.2

### ISSUE THREAD

**Issue by pasapsi** [candreoliveira/ngMask#39]
ngMask does not support js angular library 1.4.2

**Comment by celsomtrindade** [comment]
I'm using angular 1.4.2 and it's half work. It's validating the field, but for example, on a mask="99/99/999" it accept letters or other type of character. It still make the proper validation it will not be a valid input, but the user can type whatever they want.

**Comment by jakobgoldstein** [comment]
does not work with angular 1.3.15 too

**Comment by cjfringe** [comment]
Any plans to update this to support angular 1.4+?

**Comment by cjfringe** [comment]
@pasapsi I see you closed this. Is it no longer an issue?
