### ISSUE TITLE
Use ngMask on elements other than input

### ISSUE THREAD

**Issue by im1dermike** [candreoliveira/ngMask#50]
Is there a way to mask data not in an input element?  For example...

    item.ssn = 123456789;

And in HTML...

    <span mask="999-99-9999">{{item.ssn}}</span>

or even...

    {{item.ssn|mask:'999-99-9999'}}

I would expect both of these to result in `123-45-6789` being displayed.

**Comment by danielbarcellos** [comment]
My guess is that is possible. But you should work with filters then you'll have something like this. See bellow
{{item.ssn | phone}}
