### ISSUE TITLE
It's not changing mask dinamically...

### ISSUE THREAD

**Issue by Juniornativa** [candreoliveira/ngMask#54]
It doesn't change mask format dinamically based on dropdownlist state.

I need it for CPF or CNPJ

**Comment by carlos0202** [comment]
it doesnt apply mask dynamically either. We need dynamic masks please, >D

**Comment by carlos0202** [comment]
it doesnt apply mask dynamically either. We need dynamic masks please, >D

**Comment by guilhermegm** [comment]
I did that, you guys could try to use from my commit:

https://github.com/candreoliveira/ngMask/commit/9e25dcd0c15b1903392abcd220640580177db445

**Comment by aaronroberson** [comment]
Commit 9e25dcd has landed in v3.1.0

**Comment by that-medina-guy** [comment]
Is the solution for dynamic mask currently working at version 3.1.1?
Trying to bind dynamic mask through $scope property, but even though the attribute changes, the mask applied to the input field does not.

`<input type="text" mask="{{maskProperty}}">`

**EDIT:** It seems that the solution works with data-binding, by using $scope.$watch method.

**Comment by Alexreddef** [comment]
Hi Lucas,
I am new to Angular and I am intrested in your solution to dynamically re-apply mask after modifying property in my scope.
But, I cannot access ngMask to launch $watch().
And when I add ngMask to my controller in order to access it, it trashes my code...
Could you help please ?
Alex

**Comment by that-medina-guy** [comment]
Hey Alex,
I managed to build an example using dynamic masking at JSFiddle (using Angular 1.6.4).
I didn't even need to use anything related to $scope.$watch method. Can you check it out?
[https://jsfiddle.net/988dgosL/2/](https://jsfiddle.net/988dgosL/2/)

Unfortunately I'm not working at my previous project anymore, so I can't really check the code I was working with. But it seems to happen only with older versions of Angular.js (my previous project was using version 1.2).

Cheers.

**Comment by Alexreddef** [comment]
Hi Lucas,
I don't get it.
It works perfectly on your fiddle ; you use apparently angular 1.4.8 and I use 1.4.0.
ngMask.js are identical (I installed v3.1.1).
I tried to restart a simple angular project and it failed too...
RRRrrrrr !
:-)
Only thing I noticed is that on your fiddle "ngMask.generateRegex" is called when updating scope var while it isn't on my project... Can't understand why...
Thanks anyway !
Alex
 Alexandre MassoutierFabLab Manageur | http://www.innofab.fr
Tel. : 06 77 45 94 43  |  05 63 42 48 77
Un accompagnement pour vos projets, de l'idée au faire 
Permanence mar, mer, jeu AM
alexandre.massoutier@yahoo.fr

9 ans en tant qu'indépendant :
www.creativus-comunico.com


      De : Lucas Medina <notifications@github.com>
 À : candreoliveira/ngMask <ngMask@noreply.github.com> 
Cc : Alexreddef <alexreddef@yahoo.fr>; Comment <comment@noreply.github.com>
 Envoyé le : Lundi 22 mai 2017 16h28
 Objet : Re: [candreoliveira/ngMask] It's not changing mask dinamically... (#54)
  


Hey Alex,
I managed to build an example using dynamic masking at JSFiddle (using Angular 1.6.4).
I didn't even need to use anything related to $scope.$watch method. Can you check it out?
https://jsfiddle.net/988dgosL/2/Unfortunately I'm not working at my previous project anymore, so I can't really check the code I was working with. But it seems to happen only with older versions of Angular.js (my previous project was using version 1.2).Cheers.—

**Comment by Alexreddef** [comment]
Another thing I noticed is that when your code updates mask scope value, a function is called ngMask.generateRegex.But it isn't on mine. Although, both files are identical...Just FYI !Alex
 Alexandre MassoutierFabLab Manageur | http://www.innofab.fr
Tel. : 06 77 45 94 43  |  05 63 42 48 77
Un accompagnement pour vos projets, de l'idée au faire 
Permanence mar, mer, jeu AM
alexandre.massoutier@yahoo.fr

9 ans en tant qu'indépendant :
www.creativus-comunico.com


      De : Lucas Medina <notifications@github.com>
 À : candreoliveira/ngMask <ngMask@noreply.github.com> 
Cc : Alexreddef <alexreddef@yahoo.fr>; Comment <comment@noreply.github.com>
 Envoyé le : Lundi 22 mai 2017 16h28
 Objet : Re: [candreoliveira/ngMask] It's not changing mask dinamically... (#54)
   
Hey Alex,
I managed to build an example using dynamic masking at JSFiddle (using Angular 1.6.4).
I didn't even need to use anything related to $scope.$watch method. Can you check it out?
https://jsfiddle.net/988dgosL/2/Unfortunately I'm not working at my previous project anymore, so I can't really check the code I was working with. But it seems to happen only with older versions of Angular.js (my previous project was using version 1.2).Cheers.—

**Comment by sanme98** [comment]
Hi All,
I found if I using ngMask.min.js, the dynamic masking is not working. If I using ngMask.js, it is working. 

Is it the minified code is different with the unminified code?

Thank you.

**Comment by inafalcao** [comment]
@sanme98 The same thing happened to me. Using ngMask.js solved my problem with dinamically binding the mask attribute. 

I tried do minify it myself, and it seems to work. Something happened with that minification that turned the two codes different.
