### ISSUE TITLE
Cursor position if invalid

### ISSUE THREAD

**Issue by frlinw** [candreoliveira/ngMask#87]
Cursor automatically go to the end of the input if the input become invalid
It can be disturbing if you want to edit a value

mask is 99/99
I enter 1246 (->12/46)
I want to replace 2 with 9
I remove the 2 -> 14/6 and instead of staying between 1 and 4, the cursor is at the end

**Comment by Knoxvillekm** [comment]
+

**Comment by sigMacity** [comment]
++ This is the same as #78

**Comment by sergiy-talashko** [comment]
@frlinw @Knoxvillekm @sigMacity 

Fixed by adding restrict="reject".

You can read about this attr in Readme
