### ISSUE TITLE
mask defined in the variable scope

### ISSUE THREAD

**Issue by Claudio76** [candreoliveira/ngMask#9]
hello!
I am using your module, but I have a problem.
when I define the mask through a scope variable, defined mask is not working. If I put string D? S ?, insert points every 2 or 3 positions or not working properly.

**Comment by candreoliveira** [comment]
Why you don't put your mask as attribute? Take a look here: http://candreoliveira.github.io/bower_components/angular-mask/examples/index.html#/

**Comment by candreoliveira** [comment]
It should be an attribute.
