### ISSUE TITLE
Mask is not applied when model value changes from external code

### ISSUE THREAD

**Issue by a-t** [candreoliveira/ngMask#95]
Hello there!
I wonder what's the reason for deregistering a watcher [here](https://github.com/candreoliveira/ngMask/blob/master/src/directives/mask.js#L171)? Is it really necessary? The problem is it leads to the mask not being applied on model change.
[Here](http://plnkr.co/edit/34DKTnG5UNVD4f6kYL44?p=preview) is an example. Try editing the "Phone number w/o mask" field.

**Comment by aaronroberson** [comment]
The fix for this has been merge and will land in v3.1.1

**Comment by lucis** [comment]
Having the same problem working with Firebase, where the data is loaded through websocket

**Comment by a-t** [comment]
It seems that version 3.1.1 where the fix is still hasn't been released. 3.1.0 is marked as the latest release now.
